name: CD

on:
  push:
    branches:
      - main

jobs:

    Trying_encrypted_file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Decrypt large secret
          run: ./.github/scripts/decrypt_secrets.sh
          env:
            LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
            
        - name: Test printing your secret (Remove this step in production)
          run: cat $HOME/secrets/my_secret.json 
